version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: docprocessor-mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=docprocessor_dev
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - docprocessor-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: docprocessor-rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_DEFAULT_VHOST=/docprocessor
    networks:
      - docprocessor-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  mongodb_data_dev:
    driver: local
  rabbitmq_data_dev:
    driver: local

networks:
  docprocessor-network:
    driver: bridge