spring:
  application:
    name: document-processing-backend
  
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/docprocessor_dev?authSource=admin
      auto-index-creation: true
  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /docprocessor
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Sao_Paulo

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.docprocessor: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.amqp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  upload:
    directory: ./uploads
    allowed-types: application/pdf,image/jpeg,image/png,image/jpg
    max-file-size: 52428800 # 50MB in bytes
  
  processing:
    ocr-simulation-delay: 500
    timeout: 30000
  
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

---
spring:
  config:
    activate:
      on-profile: docker
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@mongodb:27017/docprocessor?authSource=admin}
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/docprocessor}
  
app:
  upload:
    directory: /app/uploads
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://frontend:3000}

logging:
  level:
    com.docprocessor: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.amqp: WARN

---
spring:
  config:
    activate:
      on-profile: test
  
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/docprocessor_test?authSource=admin
      auto-index-creation: false
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
app:
  upload:
    directory: ./test-uploads
  processing:
    ocr-simulation-delay: 50
    timeout: 5000

logging:
  level:
    com.docprocessor: WARN
    org.springframework.data.mongodb: WARN
    org.springframework.amqp: WARN